Controllers/DeseasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CompatibilityWebSite;

namespace CompatibilityWebSite.Controllers
{
    public class DeseasesController : Controller
    {
        private readonly CompatibilityWebSiteContext _context;

        public DeseasesController(CompatibilityWebSiteContext context)
        {
            _context = context;
        }

        // GET: Deseases
        public async Task<IActionResult> Index()
        {
            return View(await _context.Deseases.ToListAsync());
        }

        // GET: Deseases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var desease = await _context.Deseases
                .FirstOrDefaultAsync(m => m.Id == id);
            if (desease == null)
            {
                return NotFound();
            }

            return View(desease);
        }

        // GET: Deseases/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Deseases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Info")] Desease desease)
        {
            if (ModelState.IsValid)
            {
                _context.Add(desease);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(desease);
        }

        // GET: Deseases/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var desease = await _context.Deseases.FindAsync(id);
            if (desease == null)
            {
                return NotFound();
            }
            return View(desease);
        }

        // POST: Deseases/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Info")] Desease desease)
        {
            if (id != desease.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(desease);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeseaseExists(desease.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(desease);
        }

        // GET: Deseases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var desease = await _context.Deseases
                .FirstOrDefaultAsync(m => m.Id == id);
            if (desease == null)
            {
                return NotFound();
            }

            return View(desease);
        }

        // POST: Deseases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var desease = await _context.Deseases.FindAsync(id);
            _context.Deseases.Remove(desease);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeseaseExists(int id)
        {
            return _context.Deseases.Any(e => e.Id == id);
        }
    }
}

Controllers/QueryController.cs
using CompatibilityWebSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompatibilityWebSite.Controllers
{
    public class QueryController : Controller
    {
        private const string CONNECTION = "Server= ;Database=CompatibilityWebSite;Trusted_Connection=True;MultipleActiveResultSets=true";

        private const string Q1_PATH = @"C:\Crth\CompatibilityWebSite\Queries\Q1.sql";
        private const string Q2_PATH = @"C:\Crth\CompatibilityWebSite\Queries\Q2.sql"; 
        private const string Q3_PATH = @"C:\Crth\CompatibilityWebSite\Queries\Q3.sql"; 
        private const string Q4_PATH = @"C:\Crth\CompatibilityWebSite\Queries\Q4.sql"; 
        private const string Q5_PATH = @"C:\Crth\CompatibilityWebSite\Queries\Q5.sql"; 
        private const string Q6_PATH = @"C:\Crth\CompatibilityWebSite\Queries\A1.sql";

        private const string ERR_DES = "Хвороби, що задовольняють дану умову, відсутні";
        private const string ERR_AS = "Діючі речовини, що задовольняють дану умову, відсутні";
        private const string ERR_MED = "Ліки, що задовольняють дану умову, відсутні";

        private readonly CompatibilityWebSiteContext _context;
        public QueryController(CompatibilityWebSiteContext context)
        {
            _context = context;
        }

        public IActionResult Index(int error)
        {
           
            if (error == 1)
            {
                ViewBag.ErrorFlag = 1;
                ViewBag.QuantityError = "Введіть коректне число";
            }
            var empty = new SelectList(new List<string> { "---" });
            var anyDeseases = _context.Deseases.Any();
            var anyActiveSubstances = _context.ActiveSubstances.Any();
            var anyCompatibilityStatuses = _context.CompatibilityStatuses.Any();

            ViewBag.DeseaseIds = anyDeseases ? new SelectList(_context.Deseases, "Id", "Name") : empty;
            ViewBag.ActiveSubstanceIds = anyActiveSubstances ? new SelectList(_context.ActiveSubstances, "Id", "Name") : empty;
            ViewBag.CompatibilityStatusIds = anyCompatibilityStatuses ? new SelectList(_context.CompatibilityStatuses, "Id", "Name") : empty;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Query1(Query queryModel) // всі діючі речовини з d1
        {
            string query = System.IO.File.ReadAllText(Q1_PATH);
            query = query.Replace("d1", queryModel.DeseaseId.ToString());            
            query = query.Replace("\r\n", " ");
            query = query.Replace('\t', ' ');

            queryModel.QueryName = "Q1";
            queryModel.ActiveSubstanceNames = new List<string>();
            using (var connection = new SqlConnection(CONNECTION))
            {
                connection.Open();
                using (var command = new SqlCommand(query, connection))
                {
                    command.ExecuteNonQuery();
                    using (var reader = command.ExecuteReader())
                    {
                        int flag = 0;
                        while (reader.Read())
                        {
                            queryModel.ActiveSubstanceNames.Add(reader.GetString(0));
                            flag++;
                        }

                        if (flag == 0)
                        {
                            queryModel.ErrorFlag = 1;
                            queryModel.ErrorName = ERR_AS;
                        }
                    }
                }
                connection.Close();
            }
            return RedirectToAction("Results", queryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Query2 (Query queryModel) // всі хвороби, для яких використовується as1
        {
            string query = System.IO.File.ReadAllText(Q2_PATH);
            query = query.Replace("as1", queryModel.ActiveSubstanceId.ToString());
            query = query.Replace("\r\n", " ");
            query = query.Replace('\t', ' ');

            queryModel.QueryName = "Q2";
            queryModel.DeseaseNames = new List<string>();
            using (var connection = new SqlConnection(CONNECTION))
            {
                connection.Open();
                using (var command = new SqlCommand(query, connection))
                {
                    command.ExecuteNonQuery();
                    using (var reader = command.ExecuteReader())
                    {
                        int flag = 0;
                        while(reader.Read())
                        {
                            queryModel.DeseaseNames.Add(reader.GetString(0));
                            flag++;
                        }

                        if(flag == 0)
                        {
                            queryModel.ErrorFlag = 1;
                            queryModel.ErrorName = ERR_DES;
                        }
                    }
                }
                connection.Close();
            }
            return RedirectToAction("Results", queryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Query3(Query queryModel)// всі лікарські засоби для as1
        {
            string query = System.IO.File.ReadAllText(Q3_PATH);
            query = query.Replace("as1", queryModel.ActiveSubstanceId.ToString());
            query = query.Replace("\r\n", " ");
            query = query.Replace('\t', ' ');

            queryModel.QueryName = "Q3";
            queryModel.MedicineNames = new List<string>();
            using (var connection = new SqlConnection(CONNECTION))
            {
                connection.Open();
                using (var command = new SqlCommand(query, connection))
                {
                    command.ExecuteNonQuery();
                    using (var reader = command.ExecuteReader())
                    {
                        int flag = 0;
                        while (reader.Read())
                        {
                            queryModel.MedicineNames.Add(reader.GetString(0));
                            flag++;
                        }

                        if (flag == 0)
                        {
                            queryModel.ErrorFlag = 1;
                            queryModel.ErrorName = ERR_MED;
                        }
                    }
                }
                connection.Close();
            }
            return RedirectToAction("Results", queryModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Query4 (Query queryModel) //знайти всі діючі речовини, які з s1 з >= n іншими
        {
           if (ModelState.IsValid)
           {
                string query = System.IO.File.ReadAllText(Q4_PATH);
                query = query.Replace("s1", queryModel.CompatibilityStatusId.ToString());
                query = query.Replace("N1", queryModel.Quantity.ToString());
                query = query.Replace("\r\n", " ");
                query = query.Replace('\t', ' ');

                queryModel.QueryName = "Q4";
                queryModel.ActiveSubstanceNames = new List<string>();

                using (var connection = new SqlConnection(CONNECTION))
                {
                    connection.Open();
                    using (var command = new SqlCommand(query, connection))
                    {
                        command.ExecuteNonQuery();
                        using (var reader = command.ExecuteReader())
                        {
                            int flag = 0;
                            while (reader.Read())
                            {
                                queryModel.ActiveSubstanceNames.Add(reader.GetString(0));
                                flag++;
                            }

                            if (flag == 0)
                            {
                                queryModel.ErrorFlag = 1;
                                queryModel.ErrorName = ERR_AS;
                            }
                        }
                    }
                    connection.Close();
                }
                return RedirectToAction("Results", queryModel);
            }
            return RedirectToAction("Index", new { error = 1 });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Query5(Query queryModel) //знайти всі ліки, в яких >= n діючих речовин
        {
            if (ModelState.IsValid)
            {
                string query = System.IO.File.ReadAllText(Q5_PATH);
                query = query.Replace("N1", queryModel.Quantity.ToString());
                query = query.Replace("\r\n", " ");
                query = query.Replace('\t', ' ');

                queryModel.QueryName = "Q5";
                queryModel.MedicineNames = new List<string>();

                using (var connection = new SqlConnection(CONNECTION))
                {
                    connection.Open();
                    using (var command = new SqlCommand(query, connection))
                    {
                        command.ExecuteNonQuery();
                        using (var reader = command.ExecuteReader())
                        {
                            int flag = 0;
                            while (reader.Read())
                            {
                                queryModel.MedicineNames.Add(reader.GetString(0));
                                flag++;

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompatibilityWebSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ActiveSubstances" asp-action="Index">Діючі речовини</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compatibilities" asp-action="Index">Сумісності</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompatibilityStatus" asp-action="Index">Статуси сумісностіs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deseases" asp-action="Index">Хвороби</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DeseasesActiveSubstances" asp-action="Index">Хвороби та діючі речовини для їх лікуваня</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicineActiveSubstances" asp-action="Index">Лікарські засоби та їх діючі речовини</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicines" asp-action="Index">Лікарські засоби</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Query" asp-action="Index">Запити</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CompatibilityWebSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>